### ISSUE TITLE
Home and End button are not workable

### ISSUE THREAD

**Issue by double12gzh** [CharlesChiuGit/nvimdots.lua#7]
### Neovim version

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az178-366  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/share/nvim"  Run :checkhealth for more info

### Operating system/version

Linux laptop 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Press "HOME" button under n/i/v mode expected to jump to the begin/end of one line

### Expected behavior

Press "HOME" button under n/i/v mode expected to jump to the begin/end of one line

**Comment by CharlesChiuGit** [comment]
Have u check your alacritty config? I'm also using wsl as well. "Home" & "End" keys works for me on windows terminal.

**Comment by double12gzh** [comment]
Sorry it's my fault, this is not a bug. Just as what you said, it is releated to my alacritty...

**Comment by CharlesChiuGit** [comment]
Glad to help. Let me know if there's anything that could be better!
